APPLICATION:
  PORT: 8080
  GROUP: v1/
DB:
  POSTGRE:
    DB_HOST: 0.0.0.0
    DB_NAME: cats_social_db
    DB_PORT: 5432
    DB_USERNAME: cats_social_db_owner
    DB_PASSWORD: 4j2kxetmuPIK
    DB_PARAMS: "sslmode=disable"
AUTH:
  JWT_SECRET: Kkslskkwokwkswojwnwjiji
  # 8 houre in minute
  ACCESS_TOKEN_EXPIRED_TIME: 480
  REFRESH_TOKEN_EXPIRED_TIME: 5h
  COOKIE_SECRET:
  BCRYPT_SALT: 8