APPLICATION:
  PORT: 8080
  GROUP: v1/
DB:
  POSTGRE:
    HOST: 0.0.0.0
    NAME: cats_social_db
    PORT: 5432
    USERNAME: cats_social_db_owner
    PASSWORD: 4j2kxetmuPIK
    PARAMS: "sslmode=disable"
AUTH:
  JWT_SECRET: Kkslskkwokwkswojwnwjiji
  # 8 houre in minute
  ACCESS_TOKEN_EXPIRED_TIME: 480
  REFRESH_TOKEN_EXPIRED_TIME: 5h
  COOKIE_SECRET:
  BCRYPT_SALT: 8