APPLICATION:
  PORT: 8080
  GROUP: api/v1/
DB:
  POSTGRE:
    DB_HOT: 172.17.0.1
    DB_NAME: cats-social
    DB_PORT: 5433
    DB_USERNAME:
    DB_PASSWORD:
    DB_PARAMS: "sslmode=disabled"
AUTH:
  JWT_SECRET:
  ACCESS_TOKEN_EXPIRED_TIME: 15m
  REFRESH_TOKEN_EXPIRED_TIME: 5h
  COOKIE_SECRET:
  BCRYPT_SALT: 8